### ISSUE TITLE
uci.js

### ISSUE THREAD

**Issue by SzotsGabor** [kurt1288/KhepriChess#12]
Hello Kurt,

Will you not provide a js for use in connection with node any more?

Gabor

**Comment by kurt1288** [comment]
I can, if it would be helpful. The binaries are/were intended to replace the uci-js file.

**Comment by SzotsGabor** [comment]
Khepri is not the only js engine so I keep node installed anyway. Not particularly important but why should I use large exes instead, are they faster?

**Comment by kurt1288** [comment]
The windows exe should not be any faster or slower than the plain JS file. I can't comment on the Linux or MacOS binaries as I'm not able to test them.

My intent with the pre-compiled binary is to make it more accessible to use. And it should ensure that, even if a user has node installed, the exe will be bundled with the version I'm building and testing against so there should be no version issues with users.
