### ISSUE TITLE
nodeJS included in binaries !

### ISSUE THREAD

**Issue by tissatussa** [kurt1288/KhepriChess#14]
At the release page of v4.0.0 i read :

_..this is the first version to include precompiled binaries for UCI-compatible applications. This also means `node.js` is no longer needs to be installed prior to using (but does mean that the binaries contain `node`, which is why they're rather large files)._

indeed, the Linux asset is 44 Mb in size .. that's OK with me, but i wonder : how did you compile JS source code into a (Linux) binary, containing Node ?

i know how to create a binary of Python3 code by using PyInstaller, which works very well on my machine. Embedding Node seems interesting, until now i didn't know this was possible .. i'm familiar with default JS, not especially Node. How can i compile simple JS code into a binary ?

**Comment by kurt1288** [comment]
There's a few libraries that can package node, but the one I use is [pkg](https://github.com/vercel/pkg) to compile node to the binaries.
