### ISSUE TITLE
On the right track

### ISSUE THREAD

**Issue by SzotsGabor** [kurt1288/KhepriChess#9]
You could make it even more obvious which is which by including the version number in the file name.

Nice progress, BTW.

Gabor

**Comment by kurt1288** [comment]
That was a quick comment! Thanks.

And ya, that's a good idea. I'll aim to do that from now on.

**Comment by SzotsGabor** [comment]
I wanted to be equally quick at starting a new test run but I'm afraid it will have to wait a couple of days.
